### ISSUE TITLE
PIP installation problem

### ISSUE THREAD

**Issue by rumiak** [MarketSquare/roboswag#28]
Hi Guys,

I wanted to give you library a try in one of my API projects. Unfortunately after installation with pip, during verification I am receiving following error message:

![image](https://user-images.githubusercontent.com/68506873/179173100-d28faff6-8064-4fc0-988f-7c99dbdbc1ce.png)

Can you please give me a hint if there are any missing steps in pip installation process or should I do some investigation on my environment?

**Comment by bhirsz** [comment]
This should be fixed by #27 - I have just merged PR. Can you retest it?

It's good timing since I was heavily involved in Robotidy but in upcoming weeks I should find some time for roboswag as well - I will start with authentication and support for V3 of open API. Feep free to also report any bugs or missing features you find :)

**Comment by rumiak** [comment]
@bhirsz thank you for your update. It looks like roboswag on my local machine works fine now:

![image](https://user-images.githubusercontent.com/68506873/179212944-6715cf21-a71f-45f6-b1ef-1c900489d22f.png)

I'm closing this issue.
